---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-7.8

suites:
  - name: base
    data_bags_path: "test/integration/default/data_bags"
    run_list:
      - recipe[base::default]
    attributes:
      authorization: { sudo: { users: ["vagrant"]}}
